spring:
  application:
    name: gmall-user-manage
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

server:
  port: 8080

