server:
  port: 8083

logging:
  level:
    root: debug

spring:
  application:
    name: gmall-manage-web
dubbo:
  application:
    name: gmall-order-web
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
    timeout: 10000

fdfs:
  # 读取时间
  soTimeout: 1501
  # 连接超时时间
  connectTimeout: 691
  # 编码默认UTF-8，charset属性不能自定义
  # charset: UTF-8
  # 缩略图
  thumbImage:
    # 宽
    width: 150
    # 高
    height: 150
  # tracker列表
  trackerList:
    - 111.111.111.111:22122

fileServer:
  url: http://127.0.0.1/
